  name: Deploy Frontend to VPS
  on:
    push:
      branches: [ main ] # Altere para a branch que você usa, se for diferente
  jobs:
    deploy-frontend:
      runs-on: ubuntu-latest
      steps:
        - name: Deploy Frontend to VPS via SSH
          uses: appleboy/ssh-action@master
          with:
            host: 69.62.89.211 # IP da sua VPS
            username: root # Usuário da VPS
            key: ${{ secrets.SSH_PRIVATE_KEY }} # Nome do segredo com a chave privada
            script: |
              cd /root/sysjpj/Frontend
              git pull origin main
              npm install
              npm run build
              cp -r dist/* /var/www/html/
              systemctl reload nginx
